language: node_js
node_js:
  - '11'
  - '10'
  - '8'


stages:
  # Deploy to production
  - name: deploy
    if: branch = master

env:
  global:
    - REPO=hk-address-parser-lib
    - ORG=g0vhk

cache: npm

      
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_API_KEY
  on:
    tags: true
    all_branches: true
